name: script 2
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      COURSE_ID:
        required: true 
        type: string
      CM_ID:
        required: true 
        type: string
      GITHUB_PR_REGEX:
        required: true 
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: set config path
        run: |
          echo "PR_BOT_CONFIG_PATH=bot_config" >> "$GITHUB_ENV"
      - 
        name: workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "COURSE_ID=${{github.event.inputs.COURSE_ID}}" >> "$GITHUB_ENV"
          echo "CM_ID=${{github.event.inputs.CM_ID}}" >> "$GITHUB_ENV"
          echo "GITHUB_PR_REGEX=${{github.event.inputs.GITHUB_PR_REGEX}}" >> "$GITHUB_ENV"
      - 
        name: cron 1
        if: github.event.schedule == '*/15 * * * *'
        run: |
          echo "COURSE_ID=47" >> "$GITHUB_ENV"
          echo "CM_ID=1553" >> "$GITHUB_ENV"
          echo "GITHUB_PR_REGEX='^(\\w*)_(lr1)$'" >> "$GITHUB_ENV"
      - 
        name: Set env from secrets
        run: |
          echo "MOODLE_ACCESS_TOKEN=${{ secrets.MOODLE_ACCESS_TOKEN }}" >> "$GITHUB_ENV"
      - 
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: "000"
        run: ls "${{ github.workspace }}" .
        shell: bash
      # - 
      #   name: Run script 1
      #   run: docker run -v ${{ github.workspace }}/${{ env.PR_BOT_CONFIG_PATH }}:./configs -e COURSE_ID="${{env.COURSE_ID}}" -e CM_ID="${{env.CM_ID}}" -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="${{env.GITHUB_PR_REGEX}}" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ env.MOODLE_ACCESS_TOKEN }}" --rm fox1209/gm_scripts:1.0.3  pwd
      #   # run: docker run -v ${{ github.workspace }}/${{ env.PR_BOT_CONFIG_PATH }}:/configs -e COURSE_ID="${{env.COURSE_ID}}" -e CM_ID="${{env.CM_ID}}" -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="${{env.GITHUB_PR_REGEX}}" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ env.MOODLE_ACCESS_TOKEN }}" --rm fox1209/gm_scripts:1.0.3  python main.py script2
      #   shell: bash
      - 
        name: Run script 3
        run: docker run -v ${{ github.workspace }}/${{ env.PR_BOT_CONFIG_PATH }}:/home/jobuser/configs -e COURSE_ID="${{env.COURSE_ID}}" -e CM_ID="${{env.CM_ID}}" -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="${{env.GITHUB_PR_REGEX}}" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ env.MOODLE_ACCESS_TOKEN }}" --rm fox1209/gm_scripts:1.0.3 ls
        shell: bash

      # - 
      #   name: Run script
      #   uses: Dmitriy129/moodle-github-sync-2@0.1.3

      - run: echo "🍏 This job's status is ${{ job.status }}."